#!/usr/bin/env php
<?php

if (!$loader = include __DIR__.'/vendor/autoload.php') {
    die('You must set up the project dependencies.');
}

use Symfony\Component\Console\Application;

$app = new Application('Swarrot MailWorker');
$app->add(new Swarrot\Command\MailCommand());
$app->run();
